version: "3"
services:
  manager:
    build: ./manager
    depends_on:
      - db
    environment:
      CSV_FILENAME: data.csv
      POSTGRES_USER: antoine
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POSTGRES_DB
  db:
    image: postgres
    environment:
      CSV_FILENAME: data.csv
      POSTGRES_USER: antoine
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POSTGRES_DB

